variable "prefix" {
  description = "Prefix for all created resources"
}

variable "common_infrastructure_tfstate_bucket" {
  description = "S3 Bucket where the common terraform state resides"
}

variable "common_infrastructure_tfstate_key" {
  description = "S3 path key where the common terraform state resides"
}

variable "common_infrastructure_bucket_region" {
  description = "S3 region where the common terraform state resides"
}

variable "input_s3_path" {
  description = "Input folder on S3 including trailing /"
}

variable "output_s3_path" {
  description = "Output folder on S3 including trailing /"
}

variable "encoder_setting_s3_path" {
  description = "S3 Path to ffmpeg encoder configuration. See config/encoder-config-sample.json"
}

variable "instance_count" {
  description = "Number of instances in the cluster to do the work"
}

variable "instance_type" {
  description = "Instance type to use. Use these instance family `C3, C4, C5, M4, M5, R3, and R4, with less than 100 GB of memory.` that supports hibernation. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#interruption-behavior"
}

variable "instance_ssh_key" {
  description = "Instance SSH keypair name"
  default     = ""
}

variable "ebs_volume_size" {
  default     = 200
  description = "EBS Volume to provision in GiB (make sure it's above the RAM size and your video files)"
}

variable "source_code_repository" {
  default     = "https://github.com/michaelaw320/ffmpeg-aws-spot-cluster.git"
  description = "ffmpeg-aws-spot-cluster source code repository to clone and install"
}

variable "source_code_branch" {
  default     = "master"
  description = "Source code branch to checkout (useful for development)"
}

variable "s3_ffmpeg_bin_path" {
  default     = ""
  description = "Use custom built ffmpeg binary from S3 path. Default will use snapshot binary generated by johnvansickle.com"
}
